### ISSUE TITLE
Error when opening OME-Zarr created with bioformats2raw

### ISSUE THREAD

**Issue by tischi** [mobie/mobie-io#72] opened 2022-02-17 12:37 UTC
@constantinpape @K-Meech @KateMoreva 

`Plugins › BigDataViewer › OME ZARR › Open OME ZARR From File System...`

with 

`/g/cba/exchange/ome-zarr/2022/lifdata1__bf2raw-0-4-0.zarr`

gives

```
(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_202 [64-bit]; Mac OS X 10.14.6; 586MB of 8953MB (6%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.UnsupportedOperationException: Could not find multiscales at 
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.getMultiscale(N5OMEZarrImageLoader.java:279)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:183)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5OMEZarrImageLoader.java:134)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.<init>(N5OMEZarrImageLoader.java:122)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrOpener.readFile(OMEZarrOpener.java:45)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrOpener.openFile(OMEZarrOpener.java:23)
	at org.embl.mobie.viewer.command.OpenOMEZARRCommand.openAndShow(OpenOMEZARRCommand.java:20)
	at org.embl.mobie.viewer.command.OpenOMEZARRCommand.run(OpenOMEZARRCommand.java:28)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
```

**Comment by constantinpape** [comment] 2022-02-17 12:55
It's an encoding issue: the data is written with `$\um$m` as unit (which is also discouraged by the spec). If you change it to some unit name that is UTF-8 it works. (This is why sticking to UTF-8 is always a good idea....)

**Comment by constantinpape** [comment] 2022-02-17 13:16
> What should we do now?
> Can we support this encoding in mobie-io?
> Should bioformats2raw be changed?

Ideally this should be fixed in bioformats to raw, so that it writes utf-8 and only uses the recommended names for untits in order to be fully spec compliant.

**Comment by sbesson** [comment] 2022-02-17 13:33
Can you share the extract of the JSON which causes the issue on Mobie?
If it is possible to create a minimal reproducible scenario, this is likely something to report as an issue on https://github.com/glencoesoftware/bioformats2raw

**Comment by constantinpape** [comment] 2022-02-17 13:58
> Can you share the extract of the JSON which causes the issue on Mobie?
> If it is possible to create a minimal reproducible scenario, this is likely something to report as an issue on https://github.com/glencoesoftware/bioformats2raw

@tischi can you provide the minimal example and data for this?

I think we can go ahead with the release irrespective of this.

**Comment by constantinpape** [comment] 2022-02-17 15:27
@bugraoezdemir 
This is not the same metadata that causes the issue:
```json
{
  "multiscales" : [
    {
      "metadata" : {
        "method" : "loci.common.image.SimpleImageScaler",
        "version" : "Bio-Formats 6.8.0"
      },
      "datasets" : [
        {
          "path" : "0"
        },
        {
          "path" : "1"
        },
        {
          "path" : "2"
        }
      ],
      "version" : "0.2"
    }
  ]
}
```
I will try to discuss this with @tischi I am a bit confused here.

**Comment by tischi** [comment] 2022-02-17 15:54
```
(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_202 [64-bit]; Mac OS X 10.14.6; 67MB of 9749MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.embl.mobie.io.ome.zarr.util.ZArrayAttributes.getDatasetAttributes(ZArrayAttributes.java:69)
	at org.embl.mobie.io.ome.zarr.readers.N5OmeZarrReader.getDatasetAttributes(N5OmeZarrReader.java:232)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.getDatasetAttributes(N5OMEZarrImageLoader.java:248)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:185)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5OMEZarrImageLoader.java:134)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.<init>(N5OMEZarrImageLoader.java:122)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrOpener.readFile(OMEZarrOpener.java:45)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrOpener.openFile(OMEZarrOpener.java:23)
	at org.embl.mobie.viewer.command.OpenOMEZARRCommand.openAndShow(OpenOMEZARRCommand.java:20)
	at org.embl.mobie.viewer.command.OpenOMEZARRCommand.run(OpenOMEZARRCommand.java:28)
```

This is the error that corresponds to the image @bugraoezdemir uploaded.

**Comment by bugraoezdemir** [comment] 2022-02-17 15:58
Sorry. It was my mistake. The earlier error corresponded to another conversion.

**Comment by constantinpape** [comment] 2022-02-17 16:57
Hey @sbesson,
we had a closer look at this now and I initially mixed up some files and mistook the error.
So the issue here is that by default `bioformats2raw` writes a nested structure that we can't deal with in MoBIE.
But there is an option to write to the root level directly, which then should work for us.
So for now it seems like everything is ok in bioformats2raw; sorry for the false alarm.
(As a sidenote, we still have issues to open the no hierarchy version of the file, see #73; but this might be due to the fact that this is ome.zarr v0.2, which we haven't tested much in MoBIE.)

**Comment by tischi** [comment] 2022-02-17 17:38
>  writes a nested structure that we can't deal with in MoBIE.

Now I am a bit confused 😄 
I thought we can open a zarr with multiple images in MoBIE?
Doesn't that imply a nested folder structure, i.e. no multi-scales at the top level?

**Comment by constantinpape** [comment] 2022-02-17 19:32
@tischi your past self has wondered about this already: https://github.com/ome/ngff/issues/17
;)

**Comment by sbesson** [comment] 2022-02-17 22:23
I will leave you guys to sort out what MoBIE should or should not support 😄 Cross-linking other threads for completion:

- the default hierarchy produced by `bioformats2raw 0.4.0` is indeed a top-level Zarr group containing one or more multiscale OME-NGFF images as well as an `OME` group with the OME-XML metadata (see also https://github.com/ome/ome-zarr-py/issues/163#issuecomment-1024327654).

- a converter option exists which allows to flatten this layout and only generate the multiscales image - see https://forum.image.sc/t/dropping-the-top-layer-in-ome-zarr-data-without-losing-multiscales-metadata/63286

- `bioformats2raw 0.4.0` writes metadata following the 0.2 version of the OME-NGFF specification but work is currently ongoing to upgrade the implementation to comply with the recently released 0.4 version of the specification - see https://github.com/glencoesoftware/bioformats2raw/pull/121. I expect this should maximize the compatibility with MoBIE

**Comment by tischi** [comment] 2022-02-18 07:46
@constantinpape 
Thanks for pointing out my past self.
Then I don't really think we can speak of being able to open multiple images in MoBIE. 
This is more several times the same image, at potentially different chunking....

**Comment by constantinpape** [comment] 2022-02-18 08:52
@sbesson thanks for the pointers!

> * the default hierarchy produced by `bioformats2raw 0.4.0` is indeed a top-level Zarr group containing one or more multiscale OME-NGFF images as well as an `OME` group with the OME-XML metadata (see also
> * a converter option exists which allows to flatten this layout and only generate the multiscales image - see https://forum.image.sc/t/dropping-the-top-layer-in-ome-zarr-data-without-losing-multiscales-metadata/63286

Yes, we (at least the @bugraoezdemir and @tischi who are actually using `bioformats2raw`) are aware of the converter option now and will use it to create ome.zarr containers compatible with MoBIE.
We also want to support the nested hierarchies eventually, but it makes most sense to do this once we integrate with the metadata functionality from https://github.com/saalfeldlab/n5-imglib2, which has support for nesting already.

> Then I don't really think we can speak of being able to open multiple images in MoBIE.

Yes, we don't support it in the very general case of a nested hierarchy yet.

> This is more several times the same image, at potentially different chunking....

There is no restriction on how to use multiple images at the same hierarchy level, so it might as well be different images.

**Comment by constantinpape** [comment] 2022-03-15 17:34
This has been resolved.

**Closed by constantinpape** 2022-03-15 17:34 UTC
Labels: bug
